USE mysql;

SET GLOBAL local_infile = true;

-- Create the Demographics table of students if it doesn't exist
DROP TABLE IF EXISTS Wave;
CREATE TABLE Wave (
    w_id int,
    X1 float,
    X2 float,
    X3 float,
    X4 float,
    X5 float,
    X6 float,
    X7 float,
    X8 float,
    X9 float,
    X10 float,
    X11 float,
    X12 float,
    X13 float,
    X14 float,
    X15 float,
    X16 float,
    X17 float,
    X18 float,
    X19 float,
    X20 float,
    X21 float,
    X22 float,
    X23 float,
    X24 float,
    X25 float,
    X26 float,
    X27 float,
    X28 float,
    X29 float,
    X30 float,
    X31 float,
    X32 float,
    X33 float,
    X34 float,
    X35 float,
    X36 float,
    X37 float,
    X38 float,
    X39 float,
    X40 float,
    X41 float,
    X42 float,
    X43 float,
    X44 float,
    X45 float,
    X46 float,
    X47 float,
    X48 float,
    X49 float,
    Y1 float,
    Y2 float,
    Y3 float,
    Y4 float,
    Y5 float,
    Y6 float,
    Y7 float,
    Y8 float,
    Y9 float,
    Y10 float,
    Y11 float,
    Y12 float,
    Y13 float,
    Y14 float,
    Y15 float,
    Y16 float,
    Y17 float,
    Y18 float,
    Y19 float,
    Y20 float,
    Y21 float,
    Y22 float,
    Y23 float,
    Y24 float,
    Y25 float,
    Y26 float,
    Y27 float,
    Y28 float,
    Y29 float,
    Y30 float,
    Y31 float,
    Y32 float,
    Y33 float,
    Y34 float,
    Y35 float,
    Y36 float,
    Y37 float,
    Y38 float,
    Y39 float,
    Y40 float,
    Y41 float,
    Y42 float,
    Y43 float,
    Y44 float,
    Y45 float,
    Y46 float,
    Y47 float,
    Y48 float,
    Y49 float,
    Power1 float,
    Power2 float,
    Power3 float,
    Power4 float,
    Power5 float,
    Power6 float,
    Power7 float,
    Power8 float,
    Power9 float,
    Power10 float,
    Power11 float,
    Power12 float,
    Power13 float,
    Power14 float,
    Power15 float,
    Power16 float,
    Power17 float,
    Power18 float,
    Power19 float,
    Power20 float,
    Power21 float,
    Power22 float,
    Power23 float,
    Power24 float,
    Power25 float,
    Power26 float,
    Power27 float,
    Power28 float,
    Power29 float,
    Power30 float,
    Power31 float,
    Power32 float,
    Power33 float,
    Power34 float,
    Power35 float,
    Power36 float,
    Power37 float,
    Power38 float,
    Power39 float,
    Power40 float,
    Power41 float,
    Power42 float,
    Power43 float,
    Power44 float,
    Power45 float,
    Power46 float,
    Power47 float,
    Power48 float,
    Power49 float,
    qW float,
    Total_Power float,
    PRIMARY KEY (w_id)
);


-- Import the datasets from the CSVs
LOAD DATA LOCAL INFILE './data/wec_with_id.csv'
INTO TABLE Wave
FIELDS TERMINATED BY ','
IGNORE 1 ROWS;

-- Test the record count
SELECT count(*)
FROM Wave;

-- Check attribute count
SELECT COUNT(*) AS `columns`
FROM `information_schema`.`columns`
WHERE `table_schema` = 'mysql' 
  AND `table_name` = 'Wave';